module.exports = {
  someSidebar: {
    "Prism API Gateway": [
      "prism/getting-started",
      "prism/response-aggregation",
      "prism/request-transform",
      "prism/response-transform",
      "prism/https-and-cors",
      "prism/caching",
      "prism/authentication",
      "prism/rollback",
      "prism/rate-limiting",
      "prism/circuit-breaker",
      "prism/load-balancing",
      "prism/request-pipelining",
      "prism/web-jobs",
      "prism/hooks",
      "prism/redis-web-backends",
      "prism/streams",
      "prism/cluster",
      "prism/auto-scaling",
      { "Web Sockets": ["prism/websocket/intro"] },
    ],
    More: ["more/contributing", "more/license"],
  },
};
