module.exports = {
  someSidebar: {
    Docs: [
      "intro",
      "install",
      "getting-started",
      "response-aggregation",
      "request-transform",
      "response-transform",
      "https-and-cors",
      "caching",
      "authentication",
      "rollback",
      "rate-limiting",
      "circuit-breaker",
      "load-balancing",
      "request-pipelining",
      "web-jobs",
      "hooks",
      "redis-web-backends",
    ],
    "Web Sockets": ["websockets"],
    More: ["contributing", "license"],
  },
};
